name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [ "bug" ]
assignees:
 - ARCOOON

body:
 - type: textarea
   id: what-happened
   attributes:
    label: What happened?
    description: Tell us excactly, what happend!
    placeholder: Tell us what you see...
   validations:
    required: true

 - type: dropdown
   id: version
   attributes:
    label: Version
    description: What version of our software are you running?
    options:
     - 1.0.0 (Default)
    default: 0
   validations:
    required: true

 - type: input
   id: platform
   attributes:
    label: Platform
    description: Wich platform are you using?
    placeholder: Windows 11 / Ubuntu 24.04

 - type: dropdown
   id: browsers
   attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
     - Firefox
     - Chrome
     - Safari
     - Microsoft Edge
     - Not Listed?

 - type: textarea
   id: reproduction-steps
   attributes:
    label: Steps to reproduce the Bug
    description: Step by step reproduction of the problem
    placeholder: |
     1. Go to '...'
     2. Click on '....'

 - type: markdown
   attributes:
    value: |
     ### Thanks for taking the time to fill out this bug report!