name: Android CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: automated-build-android-app-with-github-action
      uses: amirisback/automated-build-android-app-with-github-action@2.2.4
            
