name: Shippie 🚢 - Code Review

# on:
#   pull_request:
#     branches: [main]

on:
  workflow_dispatch:

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Shippie 🚢
        uses: mattzcarey/shippie@v0.10.0
        with:
          TELEMETRY: "false"
          REVIEW_LANGUAGE: "English"
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL_STRING: "openai:gpt-5"
