name: Request Approval

on:
  workflow_call:

jobs:
  request:
    name: Request
    runs-on: ubuntu-latest

    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          approvers: ARCOOON
          minimum-approvals: 1
          issue-title: "🚀"
          issue-body: |
            New production deployment requested by @${{ github.triggering_actor }}.
